kixBG/Controllers/ClothesController.cs
using kixBG.Core.Contracts;
using kixBG.Core.Models.Brands;
using kixBG.Core.Models.Clothes;
using kixBG.Core.Models.ClothesCategories;
using kixBG.Extensions;
using kixBG.Infrastructure.Data.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using X.PagedList;

namespace kixBG.Controllers
{
    public class ClothesController : BaseController
    {
        private IClothesService clothesService;
        private ISellerService sellerService;

        public ClothesController(IClothesService clothesService, ISellerService sellerService)
        {
            this.clothesService = clothesService;
            this.sellerService = sellerService;
        }

        [AllowAnonymous]
        public async Task<IActionResult> All(string? categoryFilter, string? searchString, int? page)
        {
            List<ClothesAllModel> allModel = await clothesService.GetAllAsync();
            int pageSize = 3;
            int pagenumber = page ?? 1;
            IEnumerable<ClothesCategoryServiceModel> categories = await clothesService.AllCategoriesAsync();

            if (!string.IsNullOrEmpty(categoryFilter))
            {
                int categoryId = categories.Where(cc => cc.Name.ToLower() == categoryFilter.ToLower())
                                           .Select(cc => cc.Id).First();

                allModel = allModel.Where(c => c.CategoryId == categoryId)
                                   .ToList();
            }
            if (!string.IsNullOrEmpty(searchString))
            {
                allModel = allModel.Where(c => c.Model.ToLower().Contains(searchString.ToLower()))
                                   .ToList();
            }

            ViewBag.Categories = categories;
            return View(allModel.ToPagedList(pagenumber, pageSize));
        }

        [HttpGet]
        public async Task<IActionResult> Add()
        {
            if (!await sellerService.ExistsById(User.Id()))
            {
                return Unauthorized();
            }

            ClothesFormModel model = new ClothesFormModel();

            model.Categories = await clothesService.AllCategoriesAsync();
            model.Brands = await clothesService.AllBrandsAsync();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Add(ClothesFormModel modelToBind)
        {
            if (ModelState.IsValid == false)
            {
                modelToBind.Categories = await clothesService.AllCategoriesAsync();
                modelToBind.Brands = await clothesService.AllBrandsAsync();

                return View(modelToBind);
            }

            Clothe clotheToAdd = new Clothe();
            clotheToAdd.SellerId = await sellerService.GetSellerIdByUserId(User.Id());
            clotheToAdd.ImageURL = modelToBind.ImageURL;
            clotheToAdd.Model = modelToBind.Model;
            clotheToAdd.CategoryId = modelToBind.CategoryId;
            clotheToAdd.BrandId = modelToBind.BrandId;
            clotheToAdd.Condition = modelToBind.Condition;
            clotheToAdd.Size = modelToBind.Size;
            clotheToAdd.Price = modelToBind.Price;

            clothesService.AddAsync(clotheToAdd);

            return RedirectToAction(nameof(All));
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            Clothe clotheToEdit = await clothesService.GetItemByIdAsync(id);

            if (clotheToEdit == null)
            {
                return NotFound();
            }

            int currentSellerId = await sellerService.GetSellerIdByUserId(User.Id());

            if ((currentSellerId == 0 || clotheToEdit.SellerId != currentSellerId) && !User.IsAdmin())
            {
                return Unauthorized();
            }

            ClothesFormModel formModel = new ClothesFormModel
            {
                Id = id,
                BrandId = clotheToEdit.BrandId,
                CategoryId = clotheToEdit.CategoryId,
                ImageURL = clotheToEdit.ImageURL,
                Model = clotheToEdit.Model,
                Condition = clotheToEdit.Condition,
                Price = clotheToEdit.Price,
                Size = clotheToEdit.Size,
                Brands = await clothesService.AllBrandsAsync(),
                Categories = await clothesService.AllCategoriesAsync()
            };
            return View(formModel);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(ClothesFormModel formModel)
        {
            if (!ModelState.IsValid)
            {
                return View(formModel);
            }

            Clothe clotheToEdit = await clothesService.GetItemByIdAsync(formModel.Id);

            clotheToEdit.ImageURL = formModel.ImageURL;
            clotheToEdit.Model = formModel.Model;
            clotheToEdit.Condition = formModel.Condition;
            clotheToEdit.Price = formModel.Price;
            clotheToEdit.Size = formModel.Size;
            clotheToEdit.BrandId = formModel.BrandId;
            clotheToEdit.CategoryId = formModel.CategoryId;

            clothesService.SaveChangesAsync();

            return RedirectToAction(nameof(All));
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            Clothe clotheToCheck = await clothesService.GetItemByIdAsync(id);

            if (clotheToCheck == null)
            {
                return NotFound();
            }


            IEnumerable<BrandsServiceModel> brands = await clothesService.AllBrandsAsync();
            string brandName = brands.Where(b => b.Id == clotheToCheck.BrandId)
                .Select(b => b.Name)
                .First();

            IEnumerable<ClothesCategoryServiceModel> categories = await clothesService.AllCategoriesAsync();
            string categoryName = categories.Where(c => c.Id == clotheToCheck.CategoryId)
                .Select(b => b.Name)
                .First();

            ClothesDetailModel detailModel = new ClothesDetailModel()
            {
                Id = id,
                ImageURL = clotheToCheck.ImageURL,
                Model = clotheToCheck.Model,
                Brand = brandName,
                Category = categoryName,
                Condition = clotheToCheck.Condition,
                Size = clotheToCheck.Size,
                Price = clotheToCheck.Price,
                SellerUserId = await sellerService.GetUserIdBySellerId(clotheToCheck.SellerId),
                SellerId = clotheToCheck.SellerId
            };

            return View(detailModel);
        }

        public async Task<IActionResult> Delete(int id)
        {
            Clothe clotheToDelete = await clothesService.GetItemByIdAsync(id);
            if (clotheToDelete.SellerId != await sellerService.GetSellerIdByUserId(User.Id()) && !User.IsAdmin())
            {
                return Unauthorized();
            }
            clothesService.DeleteItem(clotheToDelete);

            return RedirectToAction(nameof(All));
        }
    }
}

kixBG/Controllers/SellerController.cs
using kixBG.Core.Contracts;
using kixBG.Core.Models.Clothes;
using kixBG.Core.Models.Seller;
using kixBG.Core.Models.Shoes;
using kixBG.Extensions;
using kixBG.Infrastructure.Data.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Security.Claims;

namespace kixBG.Controllers
{
    public class SellerController : BaseController
    {
        private ISellerService sellerService;
        private ICityService cityService;
        private IClothesService clothesService;
        private IShoesService shoesService;
        private ICountryService countryService;

        public SellerController(ISellerService sellerService, 
            ICityService cityService, 
            IClothesService clothesService, 
            IShoesService shoesService, 
            ICountryService countryService)
        {
            this.sellerService = sellerService;
            this.cityService = cityService;
            this.clothesService = clothesService;
            this.shoesService = shoesService;
            this.countryService = countryService;
        }

        [HttpGet]
        public async Task<IActionResult> Become()
        {
            if (await sellerService.ExistsById(User.Id()))
            {
                return View("AlreadySeller");
            }

            BecomeSellerFormModel model = new BecomeSellerFormModel();
            List<City> cities = await cityService.GetAllAsync();

            ViewBag.Cities = new SelectList(cities.Select(c => c.Name).ToList());

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Become(BecomeSellerFormModel model)
        {
            if (await sellerService.PhoneNumberTaken(model.PhoneNumber))
            {
                return BadRequest();
            }

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            int cityId = cityService.FindIdByName(model.City);

            await sellerService.AddAsync(User.Id(), model.Name, model.PhoneNumber, cityId);
            return RedirectToAction("Index", "Home");
        }

        public async Task<IActionResult> Profile(string? userId, int id)
        {
            if (!string.IsNullOrEmpty(userId))
            {
                id = await sellerService.GetSellerIdByUserId(userId);
            }
            Seller sellerToView = await sellerService.GetSellerById(id);
            if (sellerToView == null)
            {
                return RedirectToAction("NotASeller", "Home");
            }

            List<ShoeAllModel> sellerShoes = await shoesService.GetAllAsync();
            sellerShoes = sellerShoes.Where(s => s.SellerId == sellerToView.Id).ToList();

            List<ClothesAllModel> sellerClothes = await clothesService.GetAllAsync();
            sellerClothes = sellerClothes.Where(c => c.SellerId == sellerToView.Id).ToList();

            var cities = await cityService.GetAllAsync();
            City city = cities.Where(c => c.Id == sellerToView.CityId)
                                       .First();

            var country = await countryService.GetCountryByIdAsync(city.CountryId);

            SellerProfileModel spm = new SellerProfileModel(sellerToView, sellerShoes, sellerClothes, city.Name, country.Name);

            return View(spm);
        }
    }
}

kixBG/Controllers/ShoesController.cs
using kixBG.Core.Contracts;
using kixBG.Core.Models.Brands;
using kixBG.Core.Models.Shoes;
using kixBG.Extensions;
using kixBG.Infrastructure.Data.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using X.PagedList;

namespace kixBG.Controllers
{
    public class ShoesController : BaseController
    {
        private IShoesService shoesService;
        private ISellerService sellerService;

        public ShoesController(IShoesService shoesService, ISellerService sellerService)
        {
            this.shoesService = shoesService;
            this.sellerService = sellerService;
        }

        [AllowAnonymous]
        public async Task<IActionResult> All(string? brandFilter,string? searchString, int? page)
        {
            List<ShoeAllModel> allModel = await shoesService.GetAllAsync();
            int pageSize = 3;
            int pagenumber = page ?? 1;

            IEnumerable<BrandsServiceModel> brands = await shoesService.AllBrandsAsync();

            if (!string.IsNullOrEmpty(brandFilter))
            {
                int brandId = brands.Where(b => b.Name.ToLower() == brandFilter.ToLower())
                                           .Select(b => b.Id).First();

                allModel = allModel.Where(s => s.BrandId == brandId)
                                   .ToList();
            }
            if (!string.IsNullOrEmpty(searchString))
            {
                allModel = allModel.Where(s => s.Model.ToLower().Contains(searchString.ToLower()))
                                   .ToList();
            }

            ViewBag.Brands = brands;

            return View(allModel.ToPagedList(pagenumber, pageSize));
        }

        [HttpGet]
        public async Task<IActionResult> Add()
        {
            if (!await sellerService.ExistsById(User.Id()))
            {
                return Unauthorized();
            }

            ShoeFormModel formModel = new ShoeFormModel()
            {
                Brands = await shoesService.AllBrandsAsync()
            };
            return View(formModel);
        }

        [HttpPost]
        public async Task<IActionResult> Add(ShoeFormModel formModel)
        {
            if (!ModelState.IsValid)
            {
                return View(formModel);
            }

            Shoe shoeToAdd = new Shoe();
            shoeToAdd.SellerId = await sellerService.GetSellerIdByUserId(User.Id());
            shoeToAdd.ImageURL = formModel.ImageURL;
            shoeToAdd.BrandId = formModel.BrandId;
            shoeToAdd.Model = formModel.Model;
            shoeToAdd.Condition = formModel.Condition;
            shoeToAdd.Size = formModel.Size;
            shoeToAdd.Price = formModel.Price;

            shoesService.AddAsync(shoeToAdd);
            return RedirectToAction(nameof(All));
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            Shoe shoeToEdit = await shoesService.GetShoeByIdAsync(id);

            if (shoeToEdit == null)
            {
                return NotFound();
            }

            int currentSellerId = await sellerService.GetSellerIdByUserId(User.Id());

            if ((currentSellerId == 0 || shoeToEdit.SellerId != currentSellerId) && !User.IsAdmin())
            {
                return Unauthorized();
            }

            ShoeFormModel formModel = new ShoeFormModel
            {
                Id = id,
                BrandId = shoeToEdit.BrandId,
                ImageURL = shoeToEdit.ImageURL,
                Model = shoeToEdit.Model,
                Condition = shoeToEdit.Condition,
                Price = shoeToEdit.Price,
                Size = shoeToEdit.Size,
                Brands = await shoesService.AllBrandsAsync()
            };
            return View(formModel);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(ShoeFormModel formModel)
        {
            if (!ModelState.IsValid)
            {
                return View(formModel);
            }

            Shoe shoeToEdit = await shoesService.GetShoeByIdAsync(formModel.Id);

            shoeToEdit.ImageURL = formModel.ImageURL;
            shoeToEdit.Model = formModel.Model;
            shoeToEdit.Condition = formModel.Condition;
            shoeToEdit.Price = formModel.Price;
            shoeToEdit.Size = formModel.Size;
            shoeToEdit.BrandId = formModel.BrandId;

            shoesService.SaveChangesAsync();

            return RedirectToAction(nameof(All));
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            Shoe shoeToCheck = await shoesService.GetShoeByIdAsync(id);

            if (shoeToCheck == null)
            {
                return NotFound();
            }

            IEnumerable<BrandsServiceModel> brands = await shoesService.AllBrandsAsync();
            string brandName = brands.Where(b => b.Id == shoeToCheck.BrandId)
                .Select(b => b.Name)
                .First();

            ShoeDetailModel detailModel = new ShoeDetailModel()
            {
                Id = id,
                ImageURL = shoeToCheck.ImageURL,
                Model = shoeToCheck.Model,
                Brand = brandName,
                Condition = shoeToCheck.Condition,
                Size = shoeToCheck.Size,
                Price = shoeToCheck.Price,
                SellerId = shoeToCheck.SellerId,
                SellerUserId = await sellerService.GetUserIdBySellerId(shoeToCheck.SellerId)
            };

            return View(detailModel);
        }

        public async Task<IActionResult> Delete(int id)
        {
            Shoe clotheToDelete = await shoesService.GetShoeByIdAsync(id);
            if (clotheToDelete.SellerId != await sellerService.GetSellerIdByUserId(User.Id()) && !User.IsAdmin())
            {
                return Unauthorized();
            }
            shoesService.DeleteItem(clotheToDelete);

            return RedirectToAction(nameof(All));
        }
    }
}

kixBG/Views/Shared/_Layout.cshtml
@inject ISellerService sellerService

<!DOCTYPE html>
<html lang="en">
<head>
    <title>kixBG E-Shop</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="apple-touch-icon" href="~/img/apple-icon.png">
    <link rel="shortcut icon" type="image/x-icon" href="~/img/favicon.ico">

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-new.min.css">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-utilities.min.css">
    <link rel="stylesheet" href="~/css/templatemo.css">
    <link rel="stylesheet" href="~/css/custom.css">

    <!-- Load fonts style after rendering the layout styles -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;200;300;400;500;700;900&display=swap">
    <link rel="stylesheet" href="~/css/fontawesome.min.css">
</head>
<body>
    <header>
        <!-- Start Top Nav -->
        <nav class="navbar navbar-expand-lg bg-dark navbar-light d-none d-lg-block" id="templatemo_nav_top">
            <div class="container text-light">
                <div class="w-100 d-flex justify-content-between">
                    <div>
                        <i class="fa fa-envelope mx-2"></i>
                        <a class="navbar-sm-brand text-light text-decoration-none" href="mailto:kixbgeood@gmail.com">kixbgeood@gmail.com</a>
                        <i class="fa fa-phone mx-2"></i>
                        <a class="navbar-sm-brand text-light text-decoration-none" href="tel:0898989898">0898989898</a>
                    </div>
                    <div>
                        <a class="text-light" href="https://fb.com/" target="_blank" rel="sponsored"><i class="fab fa-facebook-f fa-sm fa-fw me-2"></i></a>
                        <a class="text-light" href="https://www.instagram.com/" target="_blank"><i class="fab fa-instagram fa-sm fa-fw me-2"></i></a>
                        <a class="text-light" href="https://twitter.com/" target="_blank"><i class="fab fa-twitter fa-sm fa-fw me-2"></i></a>
                    </div>
                </div>
            </div>
        </nav>
        <!-- Close Top Nav -->
        <!-- Header -->
        <nav class="navbar navbar-expand-lg navbar-light shadow">
            <div class="container d-flex justify-content-between align-items-center">

                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand text-success logo h1 align-self-center">
                    kixBG
                </a>

                <button class="navbar-toggler border-0" type="button" data-bs-toggle="collapse" data-bs-target="#templatemo_main_nav" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="align-self-center collapse navbar-collapse flex-fill  d-lg-flex justify-content-lg-between" id="templatemo_main_nav">
                    <div class="flex-fill">
                        <ul class="nav navbar-nav d-flex justify-content-between mx-lg-auto">
                            <li class="nav-item">
                                <a asp-area="" asp-controller="Home" asp-action="Index" class="nav-link">Home</a>
                            </li>
                            <li class="nav-item">
                                <a asp-area="" asp-controller="Home" asp-action="About" class="nav-link">About</a>
                            </li>
                            <li class="nav-item">
                                <a asp-area="" asp-controller="Home" asp-action="Shop" class="nav-link">Shop</a>
                            </li>
                            @if (User?.Identity?.IsAuthenticated ?? false)
                            {
                                @if (await sellerService.ExistsById(User.Id()))
                                {
                                    <li class="nav-item">
                                        <a asp-area="" asp-controller="Home" asp-action="ListingCategory" class="nav-link">Add <span class="text-success">listing</span></a>
                                    </li>
                                }
                                else if (!User.IsAdmin())
                                {
                                    <li class="nav-item">
                                        <a asp-area="" asp-controller="Seller" asp-action="Become" class="nav-link">Become a <span class="text-success">seller</span></a>
                                    </li>
                                }
                            }
                        </ul>
                    </div>
                    @if (User?.Identity?.IsAuthenticated ?? false)
                    {
                        <div class="navbar align-self-center d-flex">
                            @if (User.IsAdmin() == false)
                            {
                                <a asp-area="" asp-controller="Seller" asp-action="Profile" asp-route-userId="@User.Id()" class="nav-icon position-relative text-decoration-none">
                                    <i class="fa fa-fw fa-user text-dark mr-3"></i>
                                </a>
                            }
                            else
                            {
                                <span class="nav-icon position-relative text-decoration-none">
                                    Hello, Admin!
                                </span>
                            }
                            <a asp-area="Identity" asp-page="/Account/Logout" method="post" class="nav-icon position-relative text-decoration-none">
                                <strong>Log out</strong>
                            </a>
                        </div>
                    }
                    @if (!User?.Identity?.IsAuthenticated ?? false)
                    {
                        <div class="navbar align-self-center d-flex">
                            <a class="nav-icon d-none d-lg-inline text-decoration-none" href="/Identity/Account/Register">
                                <p>Register</p>
                            </a>
                            <a class="nav-icon d-none d-lg-inline text-decoration-none" href="/Identity/Account/Login">
                                <p class="text-success">Login</p>
                            </a>
                        </div>
                    }
                </div>

            </div>
        </nav>
        <!-- Close Header -->
    </header>
    <!-- Modal -->
    <div class="modal fade bg-white" id="templatemo_search" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="w-100 pt-1 mb-5 text-right">
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form action="" method="get" class="modal-content modal-body border-0 p-0">
                <div class="input-group mb-2">
                    <input type="text" class="form-control" id="inputModalSearch" name="q" placeholder="Search ...">
                    <button type="submit" class="input-group-text bg-success text-light">
                        <i class="fa fa-fw fa-search text-white"></i>
                    </button>
                </div>
            </form>
        </div>
    </div>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="bg-dark" id="tempaltemo_footer">
        <div class="container">
            <div class="row">

                <div class="col-md-4 pt-5">
                    <h2 class="h2 text-success border-bottom pb-3 border-light logo">kixBG</h2>
                    <ul class="list-unstyled text-light footer-link-list">
                        <li>
                            <i class="fa fa-phone fa-fw"></i>
                            <a class="text-decoration-none" href="tel:0898989898">0898989898</a>
                        </li>
                        <li>
                            <i class="fa fa-envelope fa-fw"></i>
                            <a class="text-decoration-none" href="mailto:kixbgeood@gmail.com">kixbgeood@gmail.com</a>
                        </li>
                    </ul>
                </div>

                <div class="col-md-4 pt-5">
                    <h2 class="h2 text-light border-bottom pb-3 border-light">Products</h2>
                    <ul class="list-unstyled text-light footer-link-list">
                        <li><a asp-area="" asp-controller="Clothes" asp-action="All" class="text-decoration-none">Clothes</a></li>
                        <li><a asp-area="" asp-controller="Clothes" asp-action="All" asp-route-categoryFilter="Tracksuit" class="text-decoration-none">Tracksuits</a></li>
                        <li><a asp-area="" asp-controller="Shoes" asp-action="All" class="text-decoration-none">Shoes</a></li>
                    </ul>
                </div>

                <div class="col-md-4 pt-5">
                    <h2 class="h2 text-light border-bottom pb-3 border-light">Further Info</h2>
                    <ul class="list-unstyled text-light footer-link-list">
                        <li><a asp-area="" asp-controller="Home" asp-action="Index" class="text-decoration-none">Home</a></li>
                        <li><a asp-area="" asp-controller="Home" asp-action="About" class="text-decoration-none">About Us</a></li>
                    </ul>
                </div>

            </div>

            <div class="row text-light mb-4">
                <div class="col-12 mb-3">
                    <div class="w-100 my-3 border-top border-light"></div>
                </div>
                <div class="col-auto me-auto">
                    <ul class="list-inline text-left footer-icons">
                        <li class="list-inline-item border border-light rounded-circle text-center">
                            <a class="text-light text-decoration-none" target="_blank" href="http://facebook.com/"><i class="fab fa-facebook-f fa-lg fa-fw"></i></a>
                        </li>
                        <li class="list-inline-item border border-light rounded-circle text-center">
                            <a class="text-light text-decoration-none" target="_blank" href="https://www.instagram.com/"><i class="fab fa-instagram fa-lg fa-fw"></i></a>
                        </li>
                        <li class="list-inline-item border border-light rounded-circle text-center">
                            <a class="text-light text-decoration-none" target="_blank" href="https://twitter.com/"><i class="fab fa-twitter fa-lg fa-fw"></i></a>
                        </li>
                    </ul>
                </div>
                <div class="col-auto">
                    <label class="sr-only" for="subscribeEmail">Email address</label>
                    <div class="input-group mb-2">
                        <input type="text" class="form-control bg-dark border-light" id="subscribeEmail" placeholder="Email address">
                        <div class="input-group-text btn-success text-light">Subscribe</div>
                    </div>
                </div>
            </div>
        </div>

        <div class="w-100 bg-black py-3">
            <div class="container">
                <div class="row pt-2">
                    <div class="col-12">
                        <p class="text-left text-light">
                            Copyright &copy; @DateTime.Now.Year kixEOOD
                        </p>
                    </div>
                </div>
            </div>
        </div>

    </footer>

    <script src="~/js/jquery-1.11.0.min.js"></script>
    <script src="~/js/jquery-migrate-1.2.1.min.js"></script>
    <script src="~/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/templatemo.js"></script>
    <script src="~/js/custom.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

kixBG/Views/Shared/_ShoesEditFormPartial.cshtml
@model ShoeFormModel

<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        <form method="post">
            <div class="form-group">
                <label asp-for="ImageURL"></label>
                <input asp-for="ImageURL" class="form-control" placeholder="Paste URL here..">
                <span asp-validation-for="ImageURL" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BrandId">Brand</label>
                <select asp-for="BrandId" class="form-control">
                    @foreach (var brand in Model.Brands)
                    {
                        if (brand.Id == Model.BrandId)
                        {
                            <option value="@brand.Id" selected>@brand.Name</option>
                        }
                        else
                        {
                            <option value="@brand.Id">@brand.Name</option>
                        }
                    }
                </select>
                <span asp-validation-for="BrandId" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Model"></label>
                <input asp-for="Model" class="form-control" placeholder="Model..">
                <span asp-validation-for="Model" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price"></label>
                <input asp-for="Price" class="form-control">
                <span asp-validation-for="Price" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Size"></label>
                <input asp-for="Size" class="form-control" placeholder="Size..(Enter '0' if none)">
                <span asp-validation-for="Size" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Condition"></label>
                <select asp-for="Condition" class="form-control">
                    <option value="1">1 - Very worn out</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5 - OK</option>
                    <option value="6">6</option>
                    <option value="7">7</option>
                    <option value="8">8</option>
                    <option value="9">9</option>
                    <option value="10">10 - Like brand new</option>
                </select>
                <span asp-validation-for="Condition" class="small text-danger"></span>
            </div>

            <input class="btn btn-primary mt-3 col-5" type="submit" value="Save" />
            <a asp-controller="Shoes" asp-action="Delete" asp-route-id="@Model.Id" class="btn btn-primary mt-3 col-5">Delete</a>
        </form>
    </div>
</div>